# Generated by Django 3.1.2 on 2020-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=256)),
                ('subject_name', models.CharField(max_length=256)),
                ('answer', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('answer_key', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('marks', models.FloatField()),
            ],
        ),
    ]
