# Generated by Django 3.1.2 on 2020-11-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answerkeys_answersheets_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerTable',
        ),
    ]
