# Generated by Django 3.1.2 on 2020-12-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201126_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkeys',
            name='subject_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
