# Generated by Django 3.1.4 on 2020-12-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201201_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='answersheet_id',
            field=models.IntegerField(unique=True),
        ),
    ]
