# Generated by Django 3.1.4 on 2020-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201202_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student_name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='subject_name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
