# Generated by Django 3.1.4 on 2020-12-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201202_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='roll_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
